[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm install"]

[start]
workingDirectory = "server"
cmd = "node index.js"

[phases.preDeploy]
cmds = []

[phases.build]
cmds = ["echo 'Building API server for Railway deployment'"]
