[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = ["cd server && npm install --production"]

[start]
workingDirectory = "server"
cmd = "node index.js"

[phases.preDeploy]
cmds = []

[phases.build]
cmds = ["echo 'Skipping build for API-only deployment'"]
